import { Injectable } from '@angular/core';

import { Biome } from './model/biome.model';
import { LevelRange } from './model/levelrange.model';
import { Encounter } from './model/encounter.model';

@Injectable({
  providedIn: 'root'
})
export class BiomesService {
  biomes: Biome[] = [
    new Biome(0, "Arctic", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "1 Giant Owl"),
        new Encounter(2, 5, "1d6+3 Kobolds"),
        new Encounter(6, 8, "1d4+3 Trappers (Commoners)"),
        new Encounter(9, 10, "1 Owl"),
        new Encounter(11, 12, "2d4 Blood Hawks"),
        new Encounter(13, 17, "2d6 Bandits"),
        new Encounter(18, 20, "Encounter ld3 winged kobolds with ld6 kobolds "),
        new Encounter(21, 25, "The partially eaten carcass of a mammoth, from which ld4 weeks of rations can be harvested"),
        new Encounter(26, 29, "2d8 hunters (tribal warriors)"),
        new Encounter(30, 35, "l half.ogre"),
        new Encounter(36, 40, "Single-file tracks in the snow that stop abruptly "),
        new Encounter(41, 45, "ld3 ice mephits"),
        new Encounter(46, 50, "l brown bear"),
        new Encounter(51, 53, "ld6 + l orcs"),
        new Encounter(54, 55, "l polar bear"),
        new Encounter(56, 57, "ld6 scouts"),
        new Encounter(58, 60, "l saber-toothed tiger"),
        new Encounter(61, 65, "A frozen pond with a jagged hole in the ice that appears recently made"),
        new Encounter(66, 68, "l berserker"),
        new Encounter(69, 70, "l ogre"),
        new Encounter(71, 72, "l griffon"),
        new Encounter(73, 75, "l druid"),
        new Encounter(76, 80, "3d4 refugees (commoners) fleeing from orcs"),
        new Encounter(81, 81, "ld3 veterans "),
        new Encounter(82, 82, "ld4 orogs "),
        new Encounter(83, 83, "2 brown bears "),
        new Encounter(84, 84, "l ore Eye ofGruumsh with 2d8 ores "),
        new Encounter(85, 85, "ld3 winter wolves "),
        new Encounter(86, 87, "ld4 yetis "),
        new Encounter(88, 88, "l half-ogre "),
        new Encounter(89, 89, "ld3 manticores "),
        new Encounter(90, 90, "l bandit captain with 2d6 bandits 91 l revenant "),
        new Encounter(92, 93, "l troll "),
        new Encounter(94, 95, "l werebear "),
        new Encounter(96, 97, "l young remorhaz "),
        new Encounter(98, 98, "l mammoth "),
        new Encounter(99, 99, "l young white dragon "),
        new Encounter(100, 100, "l frost giant"),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 5, "2 saber-toothed tigers "),
        new Encounter(6, 7, "ld4 half-ogres "),
        new Encounter(8, 10, "ld3 + l brown bears"),
        new Encounter(11, 15, "ld3 polar bears "),
        new Encounter(16, 20, "2d4 berserkers "),
        new Encounter(21, 25, "A half-ore druid tending to an injured polar bear.  If the characters assist the druid, she gives them a vial of antitoxin."),
        new Encounter(26, 30, "2d8 scouts"),
        new Encounter(31, 35, "2d4 ice mephits"),
        new Encounter(36, 40, "2d6 + l zombies aboard a galleon trapped in the ice. Searching the ship yields 2d20 days of rations."),
        new Encounter(41, 45, "l manticore"),
        new Encounter(46, 50, "2d6 + 3 orcs"),
        new Encounter(51, 53, "ld6 + 2 ogres "),
        new Encounter(54, 55, "2d4 griffons"),
        new Encounter(56, 57, "1d4 veterans "),
        new Encounter(58, 60, "1 bandit captain with 1 druid, ld3 berserkers, and 2d10 + 5 bandits"),
        new Encounter(61, 65, "1d4 hours of extreme cold (see chapter 5 of the Dungeon Master's Guide)"),
        new Encounter(66, 68, "1 young remorhaz"),
        new Encounter(69, 72, "1 orc Eye ofGruumsh with ld6 orogs and 2d8 + 6 orcs"),
        new Encounter(73, 75, "1 revenant"),
        new Encounter(76, 80, "A howl that echoes over the land for ld3 minutes"),
        new Encounter(81, 82, "ld3 mammoths"),
        new Encounter(83, 84, "1 young white dragon"),
        new Encounter(85, 86, "2d4 winter wolves"),
        new Encounter(87, 88, "ld6 + 2 yetis"),
        new Encounter(89, 90, "1d2 frost giants"),
        new Encounter(91, 92, "ld3 werebears"),
        new Encounter(93, 94, "1d4 trolls "),
        new Encounter(95, 96, "1 abominable yeti"),
        new Encounter(97, 98, "1 remorhaz"),
        new Encounter(99, 99, "1 roc"),
        new Encounter(100, 100, "2d4 young remorhazes "),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 1, "1 abominable yeti "),
        new Encounter(2, 4, "ld6 revenants "),
        new Encounter(5, 10, "1 d4 + 1 werebears "),
        new Encounter(11, 20, "ld3 young white dragons "),
        new Encounter(21, 25, "A blizzard that reduces visibility to 5 feet for ld6 hours "),
        new Encounter(26, 35, "1 roe "),
        new Encounter(36, 40, "A herd of 3d20 + 60 caribou (deer) moving through the snow "),
        new Encounter(41, 50, "ld4 mammoths "),
        new Encounter(51, 60, "ld8 + 1 trolls "),
        new Encounter(61, 65, "A mile-wide frozen lake in which the preserved corpses of strange creatures can be seen "),
        new Encounter(66, 75, "2d4 young remorhazes "),
        new Encounter(76, 80, "A crumbling ice castle littered with the frozen bod-ies of blue-skinned humanoids "),
        new Encounter(81, 90, "1 adult white dragon "),
        new Encounter(91, 96, "ld8 + 1 frost giants "),
        new Encounter(97, 99, "ld4 remorhazes "),
        new Encounter(100, 100, "1 ancient white dragon "),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 2, "2d10 revenants"),
        new Encounter(3, 4, "2d8 trolls"),
        new Encounter(5, 6, "2d10 werebears"),
        new Encounter(7, 8, "1 frost giant"),
        new Encounter(9, 10, "2d4 young remorhazes"),
        new Encounter(11, 20, "1d4 frost giants"),
        new Encounter(21, 25, "A circular patch of black ice on the ground. The air temperature around the patch is warmer than in the surrounding area, and characters who inspect the ice find bits of machinery frozen within."),
        new Encounter(26, 35, "1 ancient white dragon "),
        new Encounter(36, 40, "An adventurer frozen 6 feet under the ice; 50% chance the corpse has a rare magic item of the DM's choice"),
        new Encounter(41, 50, "1d3 abominable yetis"),
        new Encounter(51, 60, "ld4 remorhazes"),
        new Encounter(61, 65, "A 500-foot-high wall of ice that is 300 feet thick and spread across ld4 miles "),
        new Encounter(66, 75, "ld4 rocs"),
        new Encounter(76, 80, "The likeness of a stern woman with long, flowing hair, carved into the side of a mountain "),
        new Encounter(81, 90, "1dl0 frost giants with 2d4 polar bears"),
        new Encounter(91, 96, "1d3 adult white dragons"),
        new Encounter(97, 99, "2d4 abominable yetis "),
        new Encounter(100, 100, "1 ancient white dragon with ld3 young white dragons "),
      ])
    ]),
    new Biome(1, "Coastal", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "Pseudodragon"),
        new Encounter(2, 5, "2d8 crabs"),
        new Encounter(6, 10, "2d6 fishers (commomers)"),
        new Encounter(11, 11, "1d3 poisonous snakes"),
        new Encounter(12, 13, "1d6 guards protecting a stranded noble"),
        new Encounter(14, 15, "2d4 scouts"),
        new Encounter(16, 18, "2d10 merfolk"),
        new Encounter(19, 20, "1d6+2 sahuagin"),
        new Encounter(21, 25, "1d4 ghouls feeding on corpses abord the wreckage of a merchant ship.  A search uncovers 2d6 bolts of ruined silk, a 50-foot length of rope, and a barrel of salted herring."),
        new Encounter(26, 27, "1d4 winged kobolds with 1d6+1 kobolds"),
        new Encounter(28, 29, "2d6 tribal warriors"),
        new Encounter(30, 31, "3d4 kobolds"),
        new Encounter(32, 33, "2d4+5 blood hawks"),
        new Encounter(34, 35, "1d8+1 pteranodons"),
        new Encounter(36, 40, "A few dozen baby turtles struggling to make their way to the sea"),
        new Encounter(41, 42, "1d6+2 giant lizards"),
        new Encounter(43, 44, "1d6+4 giant crabs"),
        new Encounter(45, 46, "2d4 stirges"),
        new Encounter(47, 48, "2d6+3 bandits"),
        new Encounter(49, 53, "2d4 sahuagin"),
        new Encounter(54, 55, "1d6+2 scouts"),
        new Encounter(56, 60, "1 sea hag"),
        new Encounter(61, 65, "A momentary formation in the waves that looks like an enormous humanoid face"),
        new Encounter(66, 70, "l druid"),
        new Encounter(71, 75, "ld4 harpies"),
        new Encounter(76, 80, "A lone hermit (acolyte) sitting on the beach, con­templating the meaning of the multiverse "),
        new Encounter(81, 81, "ld4 berserkers"),
        new Encounter(82, 82, "ld6 giant eagles"),
        new Encounter(83, 83, "2d4 giant toads"),
        new Encounter(84, 84, "ld4 ogres or ld4 merrow"),
        new Encounter(85, 85, "3d6 sahuagin"),
        new Encounter(86, 86, "ld4 veterans"),
        new Encounter(87, 87, "ld2 plesiosauruses"),
        new Encounter(88, 88, "l bandit captain with 2d6 bandits"),
        new Encounter(89, 89, "ld3 manticores"),
        new Encounter(90, 90, "l banshee"),
        new Encounter(91, 92, "ld4 + 3 griffons"),
        new Encounter(93, 94, "l sahuagin priestess with ld3 merrow and 2d6 sahuagin"),
        new Encounter(95, 96, "l sahuagin baron"),
        new Encounter(97, 98, "l water elemental "),
        new Encounter(99, 99, "l cyclops"),
        new Encounter(100, 100, "l young bronze dragon "),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 1, "2d8 giant wolf spiders "),
        new Encounter(2, 3, "3d6 pteranodons "),
        new Encounter(4, 5, "2d4 scouts "),
        new Encounter(6, 7, "ld6 + 2 sahuagin "),
        new Encounter(8, 8, "l sea hag "),
        new Encounter(9, 10, "ld4 + l giant toads "),
        new Encounter(11, 15, "3d6 sahuagin "),
        new Encounter(16, 20, "2d6 giant eagles "),
        new Encounter(21, 25, "A pseudodragon chasing gulls through the air "),
        new Encounter(26, 29, "ld2 druids "),
        new Encounter(30, 32, "2d4 + 1 giant toads "),
        new Encounter(33, 35, "l commoner singing a dirge (day only) or l banshee (night only)"),
        new Encounter(36, 40, "A stoppered bottle containing an illegible note and half buried in the sand"),
        new Encounter(41, 43, "3 sea hags"),
        new Encounter(44, 46, "ld8 + l harpies"),
        new Encounter(47, 50, "ld4 plesiosauruses"),
        new Encounter(51, 53, "ld4 manticores"),
        new Encounter(54, 56, "2d4 ogres "),
        new Encounter(57, 60, "ldlO griffons"),
        new Encounter(61, 65, "A battle at sea between two galleons"),
        new Encounter(66, 70, "ld4 + 3 merrow"),
        new Encounter(71, 75, "A pirate crew consisting of l bandit captain, l druid, 2 berserkers, and 2dl2 bandits, all searching for buried treasure"),
        new Encounter(76, 80, "A severed humanoid hand tangled in a net"),
        new Encounter(81, 82, "l water elemental "),
        new Encounter(83, 84, "l cyclops "),
        new Encounter(85, 86, "ld4 banshees (night only) "),
        new Encounter(87, 88, "2d4 veterans "),
        new Encounter(89, 90, "l young bronze dragon"),
        new Encounter(91, 93, "ld3 cyclopes "),
        new Encounter(94, 95, "l young blue dragon"),
        new Encounter(96, 96, "l sahuagin baron with ld3 sahuagin priestesses and 2d8 sahuagin"),
        new Encounter(97, 97, "l djinni"),
        new Encounter(98, 98, "l roc"),
        new Encounter(99, 99, "l marid"),
        new Encounter(100, 100, "l storm giant"),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 1, "ld4 banshees (night only) "),
        new Encounter(2, 4, "l cyclops"),
        new Encounter(5, 8, "ld6 + 2 manticores "),
        new Encounter(9, 10, "ld8 + 2 veterans "),
        new Encounter(11, 20, "l young blue dragon "),
        new Encounter(21, 25, "A nest of ld6 dragon turtle eggs "),
        new Encounter(26, 35, "ld4 sahuagin barons "),
        new Encounter(36, 40, "A trident partially buried in the sand "),
        new Encounter(41, 50, "l young bronze dragon 51-55 l marid "),
        new Encounter(56, 60, "ld6 water elementals "),
        new Encounter(61, 65, "2d6 ghasts crawling over ld6 wrecked ships and feeding on the dead "),
        new Encounter(66, 70, "1 djinni 71-75 ld3 young bronze dragons "),
        new Encounter(76, 80, "A beached whale, dead and bloated. If it takes any damage, it explodes, and each creature within 30 feet of it must make a DC 15 Dexterity saving throw, taking 5d6 bludgeoning damage on a failed save, or half as much damage on a successful one. "),
        new Encounter(81, 82, "2d4 cyclopes "),
        new Encounter(83, 84, "l storm giant"),
        new Encounter(85, 86, "ld3 young blue dragons "),
        new Encounter(87, 88, "1 adult bronze dragon "),
        new Encounter(89, 90, "1 adult blue dragon "),
        new Encounter(91, 93, "ld3 rocs "),
        new Encounter(94, 97, "1 dragon turtle "),
        new Encounter(98, 99, "1 ancient bronze dragon "),
        new Encounter(100, 100, "1 ancient blue dragon "),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 10, "1 roc "),
        new Encounter(11, 20, "1 storm giant"),
        new Encounter(21, 25, "An adult bronze dragon fighting an adult blue dragon to the death"),
        new Encounter(26, 40, "2d6 cyclopes "),
        new Encounter(41, 50, "1 adult bronze dragon or 1 adult blue dragon"),
        new Encounter(51, 60, "ld3 djinn or ld3 marids"),
        new Encounter(61, 70, "1 dragon turtle "),
        new Encounter(71, 75, "ld3 rocs"),
        new Encounter(76, 80, "ld6 + 2 waterspouts that dance on the water before stopping abruptly"),
        new Encounter(81, 90, "ld6 young blue dragons"),
        new Encounter(91, 96, "1 ancient bronze dragon"),
        new Encounter(97, 99, "1 ancient blue dragon"),
        new Encounter(100, 100, "ld3 + 1 storm giants"),
      ])
    ]),
    new Biome(2, "Desert", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "3d8 scorpions "),
        new Encounter(2, 2, "2d4 vultures "),
        new Encounter(3, 3, "1 abandoned mule "),
        new Encounter(4, 4, "2d6 commoners with 2d4 camels bound for the distant city"),
        new Encounter(5, 5, "ld6 flying snakes"),
        new Encounter(6, 6, "2d6 hyenas or 2d6 jackals "),
        new Encounter(7, 7, "1d6 guards escorting a noble to the edge of the desert, all of them astride camels"),
        new Encounter(8, 8, "1d6 cats"),
        new Encounter(9, 9, "1 pseudodragon"),
        new Encounter(10, 10, "1d4 poisonous snakes"),
        new Encounter(11, 13, "2d4 stirges"),
        new Encounter(14, 15, "1d6 + 2 giant wolf spiders"),
        new Encounter(16, 17, "1 scout"),
        new Encounter(18, 20, "2d4 giant poisonous snakes"),
        new Encounter(21, 25, "Single-file tracks marching deeper into the desert"),
        new Encounter(26, 27, "4d4 kobolds"),
        new Encounter(28, 29, "1 jackalwere"),
        new Encounter(30, 31, "3d6 tribal warriors"),
        new Encounter(32, 33, "ld6 giant lizards "),
        new Encounter(34, 35, "1 swarm of insects "),
        new Encounter(36, 40, "An oasis surrounded by palm trees and containing the remnants of an old camp"),
        new Encounter(41, 44, "3d6 bandits "),
        new Encounter(45, 46, "ld4 constrictor snakes"),
        new Encounter(47, 48, "2d4 winged kobolds"),
        new Encounter(49, 50, "1 dust mephit "),
        new Encounter(51, 52, "ld4 giant scorpions"),
        new Encounter(53, 54, "1d4 giant spiders"),
        new Encounter(55, 55, "1 druid"),
        new Encounter(56, 57, "2d4 hobgoblins"),
        new Encounter(58, 58, "1 wight"),
        new Encounter(59, 60, "1 ogre "),
        new Encounter(61, 65, "A brass lamp lying on the ground"),
        new Encounter(66, 67, "ld4 giant vultures"),
        new Encounter(68, 68, "1 phase spider"),
        new Encounter(69, 69, "1 giant constrictor snake "),
        new Encounter(70, 71, "1 gnoll pack lord with ld3 giant hyenas"),
        new Encounter(72, 72, "ld6 + 2 gnolls"),
        new Encounter(73, 74, "1 mummy "),
        new Encounter(75, 75, "1 d3 half-ogres"),
        new Encounter(76, 80, "A pile of humanoid bones wrapped in rotting cloth "),
        new Encounter(81, 82, "1 lamia"),
        new Encounter(83, 83, "1 hobgoblin captain with 2d6 hobgoblins"),
        new Encounter(84, 84, "2d4 death dogs"),
        new Encounter(85, 86, "ld4 giant scorpions"),
        new Encounter(87, 87, "1 yuan-ti malison with 1 d4 + 1 yuan-ti "),
        new Encounter(88, 89, "1 bandit captain with 1 druid and 3d6 bandits"),
        new Encounter(90, 90, "2d4 thri-kreen"),
        new Encounter(91, 91, "1 air elemental "),
        new Encounter(92, 92, "ld3 couatls"),
        new Encounter(93, 93, "1 fire elemental"),
        new Encounter(94, 94, "ld4 gnoll fangs of Yeenoghu"),
        new Encounter(95, 95, "1 revenant"),
        new Encounter(96, 96, "1d4 weretigers"),
        new Encounter(97, 97, "1 cyclops"),
        new Encounter(98, 98, "1 young brass dragon"),
        new Encounter(99, 99, "1 medusa"),
        new Encounter(100, 100, "1 yuan-ti abomination"),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 1, "1d6 scouts"),
        new Encounter(2, 2, "2d4 jackalweres"),
        new Encounter(3, 3, "2d6 hobgoblins"),
        new Encounter(4, 4, "1d4+3 dust mephits"),
        new Encounter(5, 5, "1d6 swarms of insects"),
        new Encounter(6, 6, "1 giant constrictor snake"),
        new Encounter(7, 8, "1 lion"),
        new Encounter(9, 10, "2d4 gnolls"),
        new Encounter(11, 12, "2d6 giant toads"),
        new Encounter(13, 17, "1 mummy"),
        new Encounter(18, 20, "1d8+1 giant vultures"),
        new Encounter(21, 25, "A stone obelisk partly buried in the sand"),
        new Encounter(26, 28, "1 ogre with 1d3 half-ogres"),
        new Encounter(29, 35, "1d10 giant hyenas"),
        new Encounter(36, 40, "1d6+1 empty tents"),
        new Encounter(41, 43, "1d6+2 thri-keen"),
        new Encounter(44, 46, "2d4 yuan-ti purebloods "),
        new Encounter(47, 50, "ld6 + 3 death dogs "),
        new Encounter(51, 52, "ld3 + 1 giant toads   "),
        new Encounter(53, 53, "1 fire elemental "),
        new Encounter(54, 55, "1 hobgoblin captain with 3d4 hobgoblins "),
        new Encounter(56, 56, "ld6 + 2 ogres  "),
        new Encounter(57, 58, "ld4 lamias "),
        new Encounter(59, 60, "1 air elemental "),
        new Encounter(61, 65, "A meteorite resting at the bottom of a glassy crater  "),
        new Encounter(66, 66, "1 d4 + 1 wights  "),
        new Encounter(67, 68, "1 young brass dragon "),
        new Encounter(69, 70, "1 bandit captain with ld3 berserkers and 3d6 "),
        new Encounter(71, 72, "1 cyclops "),
        new Encounter(73, 73, "ld4 couatls  "),
        new Encounter(74, 75, "ld4 yuan-ti malisons "),
        new Encounter(76, 80, "Strong winds that kick up dust and reduce visibility to ld6 feet for ld4 hours "),
        new Encounter(81, 83, "1 revenant with 1 d3 wights  "),
        new Encounter(84, 85, "ld8 + 1 phase spiders  "),
        new Encounter(86, 87, "ld6 + 2 weretigers purebloods  "),
        new Encounter(88, 90, "2d4 gnoll fangs of yeenoghu"),
        new Encounter(91, 91, "1 young blue dragon "),
        new Encounter(92, 92, "1d4 cyclopes "),
        new Encounter(93, 93, "ld3 yuan-ti "),
        new Encounter(94, 94, "ld4 medusas "),
        new Encounter(95, 95, "1 guardian naga  "),
        new Encounter(96, 96, "ld3 young brass dragons "),
        new Encounter(97, 97, "1 efreeti "),
        new Encounter(98, 98, "1 roe "),
        new Encounter(99, 99, "1 gynosphinx "),
        new Encounter(100, 100, "1 adult brass dragon "),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 1, "1 young brass dragon "),
        new Encounter(2, 5, "4d6 gnolls "),
        new Encounter(6, 10, "3d10 giant hyenas "),
        new Encounter(11, 12, "ld8 + 1 lamias"),
        new Encounter(13, 14, "2d4 gnoll fangs of Yeenoghu "),
        new Encounter(15, 17, "ld6 + 2 giant scorpions "),
        new Encounter(18, 20, "2d4 phase spiders "),
        new Encounter(21, 25, "A desert caravan consisting of 1 d6 merchants {no-"),
        new Encounter(26, 27, "ld6 + 1 couatls "),
        new Encounter(28, 30, "ld4 fire elementals "),
        new Encounter(31, 32, "1 hobgoblin captain with 3d10 + 10 hobgoblins"),
        new Encounter(33, 35, "2d4 wights "),
        new Encounter(36, 40, "ld6 square miles of desert glass "),
        new Encounter(41, 42, "l young blue dragon "),
        new Encounter(43, 45, "ld6 + 2 weretigers "),
        new Encounter(46, 48, "ld4 air elementals "),
        new Encounter(49, 50, "1d6+1 yuan-ti malisons"),
        new Encounter(51, 55, "1d4 medusas"),
        new Encounter(56, 60, "1d4 revenants with 3d12 skeletons"),
        new Encounter(61, 65, "A plundered pyramid"),
        new Encounter(66, 70, "1d4 young brass dragons71-75 1d3 yuan-ti abominations"),
        new Encounter(76, 78, "1d6+2 cyclopes"),
        new Encounter(79, 82, "1 adult brass dragon"),
        new Encounter(83, 85, "1 purple worm"),
        new Encounter(86, 86, "1d2 young blue dragons"),
        new Encounter(87, 88, "1 mummy lord"),
        new Encounter(89, 89, "1d3 guardian nagas"),
        new Encounter(90, 90, "1 adult blue dragon91-91 1d2 gynosphinxes"),
        new Encounter(92, 93, "1d3 efreeti"),
        new Encounter(94, 94, "androsphinx"),
        new Encounter(95, 95, "1d4 rocs"),
        new Encounter(96, 97, "1 adult blue dracolich"),
        new Encounter(98, 99, "1 ancient brass dragon"),
        new Encounter(100, 100, "1 ancient blue dragon"),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 5, "adult brass dragon"),
        new Encounter(6, 10, "1d2 yuan-ti abominations with 2d10+5 yuan-ti malisons and 4d6+6 yuan-ti purebloods"),
        new Encounter(11, 14, "1d6+2 medusas"),
        new Encounter(15, 18, "1d2 purple worms"),
        new Encounter(19, 22, "2d4 cyclopes"),
        new Encounter(23, 25, "An abandoned city made from white marble, empty during the day.  At night, harmless apparitions roam the streets, replaying the final moments of their lives."),
        new Encounter(26, 30, "1d3 young blue dragons"),
        new Encounter(31, 35, "1 mummy lord"),
        new Encounter(36, 40, "1d4 hours of extreme heat (see chapter 5 of the Dungeon Master's Guide)"),
        new Encounter(41, 50, "1d3 guardian nagas"),
        new Encounter(51, 60, "1d4 efreeti"),
        new Encounter(61, 63, "An old signpost identifying a single destination, called Pazar"),
        new Encounter(64, 72, "1d4 rocs"),
        new Encounter(73, 80, "1d3 gynosphinxes"),
        new Encounter(81, 85, "1 adult blue dracolich"),
        new Encounter(86, 90, "1 androsphinx"),
        new Encounter(91, 96, "1 ancient brass dragon"),
        new Encounter(97, 99, "1 ancient blue dragon"),
        new Encounter(100, 100, "1d4 adult brass dragons"),
      ])
    ]),
    new Biome(3, "Forest", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "1 giant owl "),
        new Encounter(2, 2, "ld4 cats"),
        new Encounter(3, 3, "2d4 woodcutters (commoners) "),
        new Encounter(4, 4, "1 badger or ld4 poisonous snakes"),
        new Encounter(5, 5, "2d8 baboons "),
        new Encounter(6, 6, "ld6 + 3 hyenas"),
        new Encounter(7, 7, "1 owl "),
        new Encounter(8, 8, "1 pseudodragon "),
        new Encounter(9, 9, "1 panther "),
        new Encounter(10, 10, "1 giant poisonous snake "),
        new Encounter(11, 11, "ld6 + 2 boars "),
        new Encounter(12, 12, "l d4 + 1 giant lizards "),
        new Encounter(13, 13, "l ape or l tiger "),
        new Encounter(14, 14, "2d6 tribal warriors with ld6 mastiffs "),
        new Encounter(15, 15, "ld6 + 2 giant bats or 3d6 flying snakes "),
        new Encounter(16, 16, "l scout or 2d4 guards with ld8 mastiffs "),
        new Encounter(17, 17, "ld8 + l winged kobolds "),
        new Encounter(18, 18, "ld3 constrictor snakes "),
        new Encounter(19, 19, "ldlO + 5 giant rats or 2d6 + 3 giant weasels "),
        new Encounter(20, 20, "ld4 + 1 needle blights with ld6 + 3 twig blights "),
        new Encounter(21, 25, "A lost, weeping child. If the characters take the child home, the parents reward them with ld3 potions of healing. "),
        new Encounter(26, 26, "1d8 + 1 giant frogs "),
        new Encounter(27, 27, "4d4 kobolds "),
        new Encounter(28, 28, "ld3 black bears "),
        new Encounter(29, 29, "3d6 stirges"),
        new Encounter(30, 30, "1 satyr "),
        new Encounter(31, 31, "2d4 kenku "),
        new Encounter(32, 32, "ld3 vine blights with ld12 awakened shrubs "),
        new Encounter(33, 33, "ld4 swarms of ravens"),
        new Encounter(34, 34, "l faerie dragon "),
        new Encounter(35, 35, "ld4 + 2 giant badgers "),
        new Encounter(36, 40, "A young woodcutter (scout) racing through the forest to rescue a lost friend"),
        new Encounter(41, 41, "2d4 blink dogs "),
        new Encounter(42, 42, "1d8 + 1 sprites "),
        new Encounter(43, 43, "ld6 +2 elk"),
        new Encounter(44, 44, "ld4 lizardfolk or 3d6 bandits "),
        new Encounter(45, 45, "1 d4 + 4 wolves "),
        new Encounter(46, 46, "2d4 giant wolf spiders "),
        new Encounter(47, 47, "1 swarm of insects or 2d8 blood hawks "),
        new Encounter(48, 48, "ld6 + 2 pixies "),
        new Encounter(49, 49, "l brown bear "),
        new Encounter(50, 50, "1d4 + 3 goblins "),
        new Encounter(51, 51, "ld3 dryads "),
        new Encounter(52, 1, "wakened tree "),
        new Encounter(53, 53, "1 phase spider "),
        new Encounter(54, 54, "ld6 harpies "),
        new Encounter(55, 55, "l ettercap or ld8 + l orcs "),
        new Encounter(56, 56, "l goblin boss with 2d6 + l goblins "),
        new Encounter(57, 57, "l ankheg "),
        new Encounter(58, 58, "l giant constrictor snake "),
        new Encounter(59, 59, "ld4 bugbears or 2d4 hobgoblins "),
        new Encounter(60, 60, "l pegasus "),
        new Encounter(61, 65, "A stream of cool, clean water flowing between the trees "),
        new Encounter(66, 66, "l d4 half-ogres or l ogre "),
        new Encounter(67, 67, "l faerie dragon (green or older) "),
        new Encounter(68, 68, "l werewolf or ld8 + l worgs "),
        new Encounter(69, 69, "l druid harvesting mistletoe "),
        new Encounter(70, 70, "l will-o'-wisp "),
        new Encounter(71, 71, "ld4 dire wolves or l giant boar "),
        new Encounter(72, 71, "ldlO giant wasps "),
        new Encounter(73, 73, "l owlbear or l giant elk "),
        new Encounter(74, 74, "2d6 gnolls "),
        new Encounter(75, 75, "ld6 giant toads "),
        new Encounter(76, 80, "ld6 web cocoons hanging from the branches, hold­ing withered carcasses "),
        new Encounter(81, 81, "l wereboar or ld4 giant boars "),
        new Encounter(82, 82, "ld6 + 2 giant spiders "),
        new Encounter(83, 83, "ld4 centaurs or ld4 giant elk "),
        new Encounter(84, 84, "l ore Eye ofGruumsh with 2d4 + 2 ores"),
        new Encounter(85, 85, "l gnoll fang ofYeenoghu "),
        new Encounter(86, 86, "ld4 gricks "),
        new Encounter(87, 87, "l bandit captain with 2d6 + 3 bandits "),
        new Encounter(88, 88, "l d4 wererats "),
        new Encounter(89, 89, "l couatl (day) or l banshee (night) "),
        new Encounter(90, 90, "l gnoll pack lord with ld4 giant hyenas "),
        new Encounter(91, 91, "2d4 berserkers or ld4 veterans "),
        new Encounter(92, 92, "l lizardfofk shaman with ld3 swarms of poisonous snakes and ldlO + 2 lizardfolk "),
        new Encounter(93, 93, "ld4 displacer beasts "),
        new Encounter(94, 94, "ld3 green hags"),
        new Encounter(95, 95, "l hobgoblin captain with 2d6 hobgoblins and ld4 giant boars "),
        new Encounter(96, 96, "l yuan-ti malison with ld6 + l yuan-ti purebloods "),
        new Encounter(97, 97, "l d3 weretigers "),
        new Encounter(98, 98, "l gorgon or l unicorn "),
        new Encounter(99, 99, "l shambling mound "),
        new Encounter(100, 100, "l yuan-ti abomination "),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 1, "2d4 vine blights "),
        new Encounter(2, 2, "2d6 hobgoblins or 2d6 orcs "),
        new Encounter(3, 3, "2d4 apes or 2d4 satyrs"),
        new Encounter(4, 4, "ld3 will-o'-wisps "),
        new Encounter(5, 5, "ld4 swarms of poisonous snakes"),
        new Encounter(6, 6, "l orc Eye of Gruumsh with ld3 orcs and ld8 + 2 orcs"),
        new Encounter(7, 7, "ld3 constrictor snakes or l d4 tigers"),
        new Encounter(8, 8, "l goblin boss with 3d6 goblins "),
        new Encounter(9, 9, "l faerie dragon (any age)"),
        new Encounter(10, 10, "l brown bear or ld6 + 2 black bears"),
        new Encounter(11, 13, "ld4 giant boars"),
        new Encounter(14, 15, "ld8 + l giant spiders"),
        new Encounter(16, 17, "l lizardfolk shaman with 2d4 lizardfolk"),
        new Encounter(18, 18, "ldlO giant toads"),
        new Encounter(19, 19, "ld4 ankhegs"),
        new Encounter(20, 20, "ld3 awakened trees(day) or l banshee (night)"),
        new Encounter(21, 25, "A small shack almost hidden by the deep forest. The interior is empty aside from a large cast-iron oven."),
        new Encounter(26, 26, "l couatl"),
        new Encounter(27, 28, "ld4 ogres or ld6 + 2 half.ogres"),
        new Encounter(29, 30, "l gnoll pack lord with ld4 + l giant hyenas"),
        new Encounter(31, 32, "ld6 wererats "),
        new Encounter(33, 33, "ld4 gricks "),
        new Encounter(34, 34, "ld8 + l yuan-ti purebloods "),
        new Encounter(35, 35, "ld6 pegasi"),
        new Encounter(36, 40, "An old stone archway of obvious elven design. Any character who passes under it makes Wisdom (Perception) checks with advantage for l hour. "),
        new Encounter(41, 42, "ld6 + 2 dryads"),
        new Encounter(43, 43, "ld4 giant elk "),
        new Encounter(44, 44, "ld8 + l harpies"),
        new Encounter(45, 46, "l bandit captain with l druid and ld6 + 5 bandits "),
        new Encounter(47, 48, "2d4 dire wolves"),
        new Encounter(49, 50, "2d4 bugbears "),
        new Encounter(51, 52, "2d4 centaurs "),
        new Encounter(53, 54, "3dl0 blink dogs "),
        new Encounter(55, 56, "ld4 owl bears "),
        new Encounter(57, 58, "ld8 + l berserkers "),
        new Encounter(59, 60, "ld3 green hags "),
        new Encounter(61, 65, "A clear pool of water with ld6 sleeping animals lying around its edge "),
        new Encounter(66, 67, "1d4 werewolves"),
        new Encounter(68, 69, "l werebear"),
        new Encounter(70, 71, "ld8 + l ettercaps"),
        new Encounter(72, 73, "2dl0 elk "),
        new Encounter(74, 75, "ld4 veterans"),
        new Encounter(76, 80, "An old tree with a wizened face carved into the trunk"),
        new Encounter(81, 81, "ld4 wereboars "),
        new Encounter(82, 82, "2d4 displacer beasts"),
        new Encounter(83, 83, "ld4 shambling mounds "),
        new Encounter(84, 84, "l hobgoblin captain with 3dl0 hobgoblins and 4dl2 goblins"),
        new Encounter(85, 85, "l yuan-ti abomination"),
        new Encounter(86, 86, "ld8 + l phase spiders"),
        new Encounter(87, 87, "ld4 trolls"),
        new Encounter(88, 88, "2d4 yuan-ti malisons"),
        new Encounter(89, 89, "l oni"),
        new Encounter(90, 90, "ld4 unicorns"),
        new Encounter(91, 91, "ld6 + 2 weretigers"),
        new Encounter(92, 92, "l young green dragon"),
        new Encounter(93, 93, "ld4 gorgons"),
        new Encounter(94, 94, "ld6 + 2 gnoll fangs of Yeenoghu "),
        new Encounter(95, 95, "l treant "),
        new Encounter(96, 96, "ld4 revenants"),
        new Encounter(97, 97, "l grick alpha with ld6 + l gricks "),
        new Encounter(98, 98, "ld4 giant apes"),
        new Encounter(99, 99, "l guardian naga"),
        new Encounter(100, 100, "l adult gold dragon "),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 3, "l werebear "),
        new Encounter(4, 5, "ld4 druids performing a ritual for the dead (day only) or ld4 banshees (night only) "),
        new Encounter(6, 7, "ld3 couatls"),
        new Encounter(8, 10, "ld3 gnoll fangs of Yeenoghu with 2d6 + 3 gnolls "),
        new Encounter(11, 15, "2d4 displacer beasts "),
        new Encounter(16, 20, "ld6 + 2 veterans "),
        new Encounter(21, 25, "A pool of clear, still water. Gold coins litter the bottom, but they disappear if removed from the pool."),
        new Encounter(26, 30, "ld4 + l green hags with ld3 owlbears "),
        new Encounter(31, 35, "ld6 + 2 werewolves"),
        new Encounter(36, 40, "A small woodland shrine dedicated to a mysterious cult named the Siswa "),
        new Encounter(41, 45, "ld6 + 2 phase spiders"),
        new Encounter(46, 50, "2d4 yuan-ti malisons"),
        new Encounter(51, 52, "ld3 werebears"),
        new Encounter(53, 54, "ld4 revenants"),
        new Encounter(55, 56, "l young green dragon "),
        new Encounter(57, 58, "1d4 trolls "),
        new Encounter(59, 60, "ld6 + 2 wereboars"),
        new Encounter(61, 65, "A group of seven people (commoners) wearing animal masks and ambling through the woods "),
        new Encounter(66, 67, "ld4 gorgons "),
        new Encounter(68, 69, "ld3 shambling mounds "),
        new Encounter(70, 71, "l treant "),
        new Encounter(72, 73, "ld4 unicorns"),
        new Encounter(74, 75, "ld6 + 2 weretigers"),
        new Encounter(76, 80, "Peals of silvery laughter that echo from a distance "),
        new Encounter(81, 82, "l guardian naga"),
        new Encounter(83, 84, "l young gold dragon "),
        new Encounter(85, 86, "1 grick alpha with 2d4 gricks "),
        new Encounter(87, 88, "ld3 yuan-ti abominations "),
        new Encounter(89, 90, "l adult green dragon "),
        new Encounter(91, 93, "ld8 + l giant apes "),
        new Encounter(94, 96, "2d4 oni "),
        new Encounter(97, 99, "ld3 treants "),
        new Encounter(100, 100, "l ancient green dragon "),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 5, "l young green dragon "),
        new Encounter(6, 10, "l treant "),
        new Encounter(11, 13, "l guardian naga "),
        new Encounter(14, 16, "l dl0 revenants "),
        new Encounter(17, 19, "ld8 + l unicorns "),
        new Encounter(20, 22, "ld3 grick alphas "),
        new Encounter(23, 25, "For a few hundred feet, wherever the characters step, Flowers bloom and emit soft light. "),
        new Encounter(26, 28, "l young gold dragon "),
        new Encounter(29, 31, "ld6 + 2 shambling mounds "),
        new Encounter(32, 34, "2d4 werebears"),
        new Encounter(35, 37, "ld4 oni "),
        new Encounter(38, 40, "4d6 + 10 elves living in a small community in the treetops "),
        new Encounter(41, 43, "ld6 + 2 gorgons "),
        new Encounter(44, 46, "2d4 trolls "),
        new Encounter(47, 49, "ld4 giant apes "),
        new Encounter(50, 52, "ld3 yuan-ti abominations "),
        new Encounter(53, 62, "ld3 young green dragons "),
        new Encounter(63, 65, "A 5O-foot-tall stone statue of an elf warrior with hand raised, palm out, as if to forbid travelers from coming this way 66-7S ld4 treants "),
        new Encounter(76, 80, "A cairn set atop a low hill "),
        new Encounter(81, 90, "l adult gold dragon "),
        new Encounter(91, 96, "l ancient green dragon "),
        new Encounter(97, 99, "2d4 + l treants "),
        new Encounter(100, 100, "l ancient gold dragon"),
      ])
    ]),
    new Biome(4, "Hill", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "l eagle "),
        new Encounter(2, 3, "2d4 baboons "),
        new Encounter(4, 6, "ld6 bandits "),
        new Encounter(7, 7, "ld4 vultures "),
        new Encounter(8, 8, "ldlO commoners "),
        new Encounter(9, 9, "l raven "),
        new Encounter(10, 10, "l poisonous snake "),
        new Encounter(11, 13, "2d6 bandits or 2d6 tribal warriors "),
        new Encounter(14, 14, "2d8 goats "),
        new Encounter(15, 15, "ld6 + 4 blood hawks"),
        new Encounter(16, 16, "ld4 + 3 giant weasels "),
        new Encounter(17, 18, "ld3 guards with ld2 mastiffs and l mule "),
        new Encounter(19, 20, "ld6 + 5 hyenas "),
        new Encounter(21, 22, "2d4 stirges "),
        new Encounter(23, 25, "An empty cave littered with bones "),
        new Encounter(26, 26, "l pseudodragon or ld3 giant owls "),
        new Encounter(27, 27, "l lion or l panther (cougar) "),
        new Encounter(28, 30, "2d8 kobolds "),
        new Encounter(31, 31, "l hippogriff "),
        new Encounter(32, 34, "2d4 goblins "),
        new Encounter(35, 35, "l worg "),
        new Encounter(36, 36, "ld3 swarms of bats or ld3 swarms of ravens "),
        new Encounter(37, 37, "1 giant eagle"),
        new Encounter(38, 40, "An old dwarf sitting on a stump, whittling a piece of wood "),
        new Encounter(41, 41, "ld4 elk "),
        new Encounter(42, 42, "ld4 winged kobolds with ld6 kobolds "),
        new Encounter(43, 43, "ld6 + 2 giant wolf "),
        new Encounter(45, 45, "2d4 wolves "),
        new Encounter(46, 46, "l swarm of insects "),
        new Encounter(47, 47, "ld8 + l axe beaks "),
        new Encounter(48, 49, "l brown bear or ld3 boars "),
        new Encounter(50, 50, "1 scout "),
        new Encounter(51, 51, "l ogre "),
        new Encounter(52, 53, "2d4 gnolls "),
        new Encounter(54, 54, "l giant elk "),
        new Encounter(55, 55, "ld3 + l harpies "),
        new Encounter(56, 56, "l werewolf "),
        new Encounter(57, 58, "2d4 ores "),
        new Encounter(59, 59, "ld4 half-ogres "),
        new Encounter(60, 60, "l druid or l veteran"),
        new Encounter(61, 63, "The corpse of an adventurer that carries an intact explorer's pack and lies atop a longsword "),
        new Encounter(64, 64, "l green hag "),
        new Encounter(65, 66, "ld3 dire wolves "),
        new Encounter(67, 68, "A small cemetery containing 2d6 graves "),
        new Encounter(69, 70, "l hobgoblin captain with 2d4 hobgoblins "),
        new Encounter(71, 71, "2d4 giant goats "),
        new Encounter(72, 72, "l manticore "),
        new Encounter(73, 74, "ld6 + 2 hobgoblins "),
        new Encounter(75, 75, "1 phase spider "),
        new Encounter(76, 78, "A pile of droppings from a very large bird "),
        new Encounter(79, 79, "1 gnoll fang of Yeenoghu "),
        new Encounter(80, 80, "ld3 giant boars "),
        new Encounter(81, 81, "1 gnoll pack lord with ld3 giant hyenas "),
        new Encounter(82, 82, "1 bandit captain with 2d4 bandits "),
        new Encounter(83, 83, "1 ore Eye of Gruumsh with ld8 + 2 orcs "),
        new Encounter(84, 84, "ld3 orogs or ld4 berserkers "),
        new Encounter(85, 86, "1 ettin or 1 wereboar "),
        new Encounter(87, 88, "1 goblin boss with 2d6 "),
        new Encounter(89, 89, "ld3 griffons "),
        new Encounter(90, 90, "ld3 perytons or ld4 pegasi "),
        new Encounter(91, 96, "ld3 trolls "),
        new Encounter(97, 99, "1 cyclops "),
        new Encounter(100, 100, "1 stone giant "),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 1, "pegasi or 1d3 perytons"),
        new Encounter(2, 2, "1d6+2 giant goats"),
        new Encounter(3, 3, "1 manticore"),
        new Encounter(4, 4, "1d8+1 gnolls or 1d8+1 hobgoblins"),
        new Encounter(5, 5, "1d4 lions"),
        new Encounter(6, 6, "1d6+2 worgs"),
        new Encounter(7, 7, "1d4 brown bears"),
        new Encounter(8, 8, "3d6 axe beaks"),
        new Encounter(9, 9, "1 half-ogre with 2d6 orcs"),
        new Encounter(10, 10, "2d10 winged kobolds"),
        new Encounter(11, 12, "1 goblin boss with 1d4 dire spiders and 2d6 goblins"),
        new Encounter(13, 13, "1d6 giant elk"),
        new Encounter(14, 15, "1d8+1 giant eagles"),
        new Encounter(16, 17, "1d4 phase spiders"),
        new Encounter(18, 19, "1 gnoll pack lord with 2d4 giant hyenas"),
        new Encounter(20, 20, "2d4 hippogriffs"),
        new Encounter(21, 25, "A 15 ft tall stone statue of a dwarf warrior that has been tipped over on its side"),
        new Encounter(26, 27, "2d4 orogs"),
        new Encounter(28, 29, "1d4+1 griffons"),
        new Encounter(30, 31, "1d6+2 harpies "),
        new Encounter(32, 33, "1 orc Eye of Gruumsh with 2d6+3 orcs"),
        new Encounter(34, 35, "1d4+3 giant boars"),
        new Encounter(36, 40, "A stone door set into the side of a streep hill, opening onto 15 feet of descending stairs that end at a cave-in"),
        new Encounter(41, 42, "1d3 green hags"),
        new Encounter(43, 44, "1d4 werewolves"),
        new Encounter(45, 46, "1d6+2 ogres"),
        new Encounter(47, 48, "1 hobgoblin captain with 2d8 hobgoblins"),
        new Encounter(49, 50, "1 bandit captain with 3d6 bandits"),
        new Encounter(51, 54, "1 chimera"),
        new Encounter(55, 58, "1d4 ettins"),
        new Encounter(59, 62, "1d6+2 veterans with 2d6 berserkers"),
        new Encounter(63, 65, "An abandoned wooden hut"),
        new Encounter(66, 69, "1 galeb duhr"),
        new Encounter(70, 73, "1 bulettes"),
        new Encounter(74, 77, "1 wyvern"),
        new Encounter(78, 80, "2d6+10 goats with 1 herder (tribal warrior)"),
        new Encounter(81, 82, "1d3 hill giant"),
        new Encounter(83, 84, "2d4 wereboars"),
        new Encounter(85, 86, "1d4 revenants"),
        new Encounter(87, 88, "1d2 gorgons"),
        new Encounter(89, 90, "1d8+1 gnolls fangs of Yeenoghu"),
        new Encounter(91, 93, "1d4 cyclopes"),
        new Encounter(94, 96, "1 young red dragon"),
        new Encounter(97, 98, "1d4 stone giants"),
        new Encounter(99, 99, "1d3 young copper dragons"),
        new Encounter(100, 100, "1 roc "),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 1, "2d8 manticores or 2d8 phase spiders"),
        new Encounter(2, 4, "ld6 green hags with ld6 wyverns"),
        new Encounter(5, 7, "l hobgoblin captain with l hill giant and 4dl0 hobgoblins "),
        new Encounter(8, 10, "2d6 + 3 werewolves "),
        new Encounter(11, 14, "ld6 + 2 ettins"),
        new Encounter(15, 18, "ld3 bulettes "),
        new Encounter(19, 22, "ld4 werebears "),
        new Encounter(23, 24, "A stream of smoke emerging from a small chimney in the hillside "),
        new Encounter(25, 28, "ld4 wyverns "),
        new Encounter(29, 32, "ld8 + l wereboars "),
        new Encounter(33, 36, "ld3 revenants "),
        new Encounter(37, 38, "A mild earthquake that shakes the region for ld20 seconds "),
        new Encounter(39, 42, "ld3 chimeras "),
        new Encounter(43, 46, "ld4 gorgons "),
        new Encounter(47, 50, "ld6 + 2 gnoll fangs of Yeenoghu "),
        new Encounter(51, 54, "ld4 hill giants "),
        new Encounter(55, 58, "l young red dragon "),
        new Encounter(59, 62, "ld3 + l galeb duhr "),
        new Encounter(63, 65, "2dl0 dwarf miners (commoners), whistling as they march toward their mine "),
        new Encounter(66, 69, "ld3 young copper dragons "),
        new Encounter(70, 73, "ld4 trolls "),
        new Encounter(74, 77, "ld3 cyclopes "),
        new Encounter(78, 80, "ld3 nobles with ld4 scouts prospecting for gold "),
        new Encounter(81, 85, "l adult copper dragon"),
        new Encounter(86, 90, "2d4 stone giants"),
        new Encounter(91, 96, "ld4 rocs"),
        new Encounter(97, 99, "l adult red dragon"),
        new Encounter(100, 100, "l ancient copper dragon "),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 1, "ld2 rocs"),
        new Encounter(2, 5, "l young red dragon"),
        new Encounter(6, 10, "2d6 ettins"),
        new Encounter(11, 15, "ld4 bulettes"),
        new Encounter(16, 20, "ldl0 revenants "),
        new Encounter(21, 25, "The white outline of an enormous horse carved into the side of a high hill"),
        new Encounter(26, 30, "ld6 + l gorgons"),
        new Encounter(31, 35, "2d4 + l trolls "),
        new Encounter(36, 40, "The scorched remains of 2dl0 humanoids littering a hillside "),
        new Encounter(41, 45, "2d4 hill giants "),
        new Encounter(46, 50, "ld6 + 2 werebears "),
        new Encounter(51, 55, "2d4 galeb duhr "),
        new Encounter(56, 60, "ld4 + 2 wyvern"),
        new Encounter(61, 65, "A massive boulder partly buried in the earth as if it fell or was thrown there "),
        new Encounter(66, 70, "1 adult copper dragon "),
        new Encounter(71, 75, "ld6 + 3 cyclopes "),
        new Encounter(76, 80, "The stub of an old stone tower jutting from the top of a hill "),
        new Encounter(81, 85, "2d4 stone giants"),
        new Encounter(86, 90, "1 adult red dragon "),
        new Encounter(91, 96, "1 ancient copper dragon"),
        new Encounter(97, 99, "1 ancient red dragon "),
        new Encounter(100, 100, "ld2 adult red dragons with ld3 young red dragons "),
      ])
    ]),
    new Biome(5, "Mountain", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 2, "1 eagle"),
        new Encounter(3, 5, "1d3 swarms of bats"),
        new Encounter(6, 8, "1d6 goats"),
        new Encounter(9, 11, "1d10 + 5 tribal warriors"),
        new Encounter(12, 14, "1d6 + 3 pteranodons"),
        new Encounter(15, 17, "1d8 + 1 winged kobolds"),
        new Encounter(18, 20, "1 lion"),
        new Encounter(21, 24, "Stairs chiseled into the side of the mountain that climb 3d20 + 40 feet before ending abruptly"),
        new Encounter(25, 27, "2d10 stirges"),
        new Encounter(28, 30, "2d4 aarakocra"),
        new Encounter(31, 33, "2d6 dwarf soldiers (guards) with 1d6 mules laden with iron ore"),
        new Encounter(34, 36, "1 giant eagle"),
        new Encounter(37, 38, "A small shrine dedicated to a lawful neutral god, perched on a stone outcropping"),
        new Encounter(39, 41, "2d8 + 1 blood hawks"),
        new Encounter(42, 44, "1 giant goat"),
        new Encounter(45, 47, "3d4 kobolds"),
        new Encounter(48, 50, "1 half-ogre"),
        new Encounter(51, 53, "1 berserker"),
        new Encounter(54, 55, "1 orog"),
        new Encounter(56, 56, "1 hell hound"),
        new Encounter(57, 57, "1 druid"),
        new Encounter(58, 59, "1 peryton"),
        new Encounter(60, 61, "1d2 hippogriffs"),
        new Encounter(62, 62, "1 manticore"),
        new Encounter(63, 64, "1d6 + 2 scouts"),
        new Encounter(65, 67, "Enormous footprints left by a giant, which head into the mountain peaks"),
        new Encounter(68, 73, "2d4 orcs"),
        new Encounter(74, 75, "1 giant elk"),
        new Encounter(76, 77, "1 veteran"),
        new Encounter(78, 79, "1 orc Eye of Gruumsh"),
        new Encounter(80, 80, "1d4 harpies"),
        new Encounter(81, 81, "1 ogre"),
        new Encounter(82, 82, "1 griffon"),
        new Encounter(83, 83, "1 basilisk"),
        new Encounter(84, 85, "1 saber-toothed tiger"),
        new Encounter(86, 90, "A sparkling stream of water spilling from a crevice"),
        new Encounter(91, 91, "1d2 ettins"),
        new Encounter(92, 92, "1 cyclops"),
        new Encounter(93, 93, "1 troll"),
        new Encounter(94, 94, "1 galeb duhr"),
        new Encounter(95, 95, "1 air elemental"),
        new Encounter(96, 96, "1 bulette"),
        new Encounter(97, 97, "1 chimera"),
        new Encounter(98, 98, "1 wyvern"),
        new Encounter(99, 99, "1 stone giant"),
        new Encounter(100, 100, "1 frost giant"),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 2, "2d8 + 1 aarakocra"),
        new Encounter(3, 4, "1 lion or 1 saber-toothed tiger"),
        new Encounter(5, 6, "1d8 + 1 giant goats"),
        new Encounter(7, 8, "1d4 + 3 dwarf trailblazers (scouts)"),
        new Encounter(9, 10, "1d6 + 2 orcs"),
        new Encounter(11, 15, "1d10 giant eagles"),
        new Encounter(16, 20, "1d8 + 1 hippogriffs"),
        new Encounter(21, 25, "1d8 fissures venting steam that partially obscures a 20-foot cube above each fissure"),
        new Encounter(26, 30, "1 basilisk"),
        new Encounter(31, 35, "1d12 half-ogres"),
        new Encounter(36, 40, "A ravine blocked by a 100-foot-high wall, which has an opening in the center where a gate used to be"),
        new Encounter(41, 45, "1 manticore"),
        new Encounter(46, 50, "2d4 harpies"),
        new Encounter(51, 52, "1 galeb duhr"),
        new Encounter(53, 54, "1 bulette"),
        new Encounter(55, 56, "1d10 berserkers"),
        new Encounter(57, 58, "1d3 hell hounds"),
        new Encounter(59, 60, "1d8 + 1 veterans"),
        new Encounter(61, 65, "A distant mountain whose peak resembles a tooth"),
        new Encounter(66, 69, "1d4 ettins"),
        new Encounter(70, 73, "1 wyvern"),
        new Encounter(74, 75, "1 orc Eye of Gruumsh with 1d6 orogs and 3d6 + 10 orcs"),
        new Encounter(76, 80, "A row of 1d10 + 40 stakes upon which the bodies of kobolds, dwarves, or orcs are impaled"),
        new Encounter(81, 83, "1 fire giant"),
        new Encounter(84, 85, "1 young silver dragon"),
        new Encounter(86, 87, "1d4 air elementals"),
        new Encounter(88, 90, "1d4 trolls"),
        new Encounter(91, 92, "1d3 + 1 cyclopes"),
        new Encounter(93, 94, "1d4 chimeras"),
        new Encounter(95, 96, "1 cloud giant"),
        new Encounter(97, 97, "1 roc"),
        new Encounter(98, 98, "1d4 stone giants"),
        new Encounter(99, 99, "1 young red dragon"),
        new Encounter(100, 100, "1d4 frost giants"),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 2, "1d8 + 1 basilisks"),
        new Encounter(3, 4, "2d4 hell hounds"),
        new Encounter(5, 6, "1d3 chimeras"),
        new Encounter(7, 8, "1 galeb duhr"),
        new Encounter(9, 10, "2d6 veterans"),
        new Encounter(11, 15, "1 young silver dragon"),
        new Encounter(16, 20, "2d4 trolls"),
        new Encounter(21, 25, "1 red dragon gliding through the sky above the highest mountaintops"),
        new Encounter(26, 30, "1d8 + 1 manticores"),
        new Encounter(31, 35, "1d4 cyclopes"),
        new Encounter(36, 40, "Heavy snowfall that lasts for 1d6 hours"),
        new Encounter(41, 45, "1d10 air elementals"),
        new Encounter(46, 50, "1d6 + 2 bulettes"),
        new Encounter(51, 55, "1d4 stone giants"),
        new Encounter(56, 60, "1 fire giant"),
        new Encounter(61, 65, "2 stone giants playing catch with a boulder a few hundred feet away"),
        new Encounter(66, 70, "1d8 + 1 ettins"),
        new Encounter(71, 75, "1d3 frost giants"),
        new Encounter(76, 80, "A wide crevasse, its depths shrouded in mist"),
        new Encounter(81, 85, "1d4 cloud giants"),
        new Encounter(86, 90, "1 adult silver dragon"),
        new Encounter(91, 96, "1 adult red dragon"),
        new Encounter(97, 98, "1d4 rocs"),
        new Encounter(99, 99, "1 ancient silver dragon"),
        new Encounter(100, 100, "1 ancient red dragon"),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 5, "1d10 bulettes"),
        new Encounter(6, 10, "1d8 + 1 chimeras"),
        new Encounter(11, 15, "1 adult silver dragon"),
        new Encounter(16, 20, "1d8 + 1 wyverns"),
        new Encounter(21, 25, "A massive boat perched atop a mountain"),
        new Encounter(26, 30, "2d4 galeb duhr"),
        new Encounter(31, 35, "1d4 frost giants"),
        new Encounter(36, 40, "A wooded valley haunted by secretive and reclusive elves who tell warily of their master: a mad wizard who lives in the heart of the valley"),
        new Encounter(41, 45, "1d10 air elementals"),
        new Encounter(46, 50, "1d6 + 3 trolls"),
        new Encounter(51, 55, "1 adult red dragon"),
        new Encounter(56, 60, "1d4 cloud giants"),
        new Encounter(61, 65, "A waterfall hundreds of feet high that drops into a clear pool"),
        new Encounter(66, 70, "1d3 fire giants"),
        new Encounter(71, 75, "2d4 stone giants"),
        new Encounter(76, 80, "A force of 100 dwarves (veterans) standing guard at a mountain pass, permitting no passage until a traveler pays 100 gp (if on foot) or 200 gp (if mounted)"),
        new Encounter(81, 85, "1d4 rocs"),
        new Encounter(86, 90, "1d4 young red dragons"),
        new Encounter(91, 96, "1 ancient silver dragon"),
        new Encounter(97, 100, "1 ancient red dragon"),
      ])
    ]),
    new Biome(6, "Swamp", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "1d4 poisonous snakes"),
        new Encounter(2, 5, "3d6 rats"),
        new Encounter(6, 10, "2d8 ravens"),
        new Encounter(11, 12, "3d6 giant rats"),
        new Encounter(13, 13, "1d10 + 5 tribal warriors"),
        new Encounter(14, 15, "1d8 + 1 giant lizards"),
        new Encounter(16, 17, "1 crocodile"),
        new Encounter(18, 19, "1 swarm of insects"),
        new Encounter(20, 20, "1 giant spider"),
        new Encounter(21, 22, "1d4 + 1 mud huts partially sunken in murky water"),
        new Encounter(23, 25, "2d8 + 1 kobolds"),
        new Encounter(26, 26, "2d4 mud mephits"),
        new Encounter(27, 29, "1d6 + 2 giant poisonous snakes"),
        new Encounter(30, 30, "2d4 winged kobolds"),
        new Encounter(31, 32, "1 scout"),
        new Encounter(33, 34, "The corpse of an adventurer tangled in the weeds. Looting the body turns up an explorer's pack and perhaps (50% chance) a random common magic item."),
        new Encounter(35, 38, "1 giant toad"),
        new Encounter(39, 41, "1d6 + 2 constrictor snakes"),
        new Encounter(42, 44, "2d4 giant frogs"),
        new Encounter(45, 45, "1d8 + 1 swarms of rats or 1d6 + 2 swarms of ravens"),
        new Encounter(46, 48, "2d10 stirges"),
        new Encounter(49, 52, "2d6 + 3 bullywugs"),
        new Encounter(53, 54, "1d8 + 1 orcs"),
        new Encounter(55, 56, "1d4 yuan-ti purebloods"),
        new Encounter(57, 57, "1 druid"),
        new Encounter(58, 59, "1 yuan-ti malison"),
        new Encounter(60, 62, "1 giant constrictor snake"),
        new Encounter(63, 64, "A high-pitched shriek that lasts for 1d4 minutes"),
        new Encounter(65, 67, "2d4 lizardfolk"),
        new Encounter(68, 69, "1d4 ghouls"),
        new Encounter(70, 71, "1 will-o'-wisp"),
        new Encounter(72, 72, "1 wight"),
        new Encounter(73, 73, "1 ghast"),
        new Encounter(74, 75, "1 swarm of poisonous snakes"),
        new Encounter(76, 77, "A foul stench bubbling up from brackish waters"),
        new Encounter(78, 80, "1d4 + 2 ogres"),
        new Encounter(81, 83, "1 shambling mound"),
        new Encounter(84, 86, "1 lizardfolk shaman with 1d6 giant lizards and 2d10 lizardfolk"),
        new Encounter(87, 87, "1 troll"),
        new Encounter(88, 89, "1d4 green hags"),
        new Encounter(90, 91, "1 revenant"),
        new Encounter(92, 93, "1 giant crocodile"),
        new Encounter(94, 95, "1 orc Eye of Gruumsh with 1d3 orogs and 2d6 + 3 orcs"),
        new Encounter(96, 97, "1 young black dragon"),
        new Encounter(98, 98, "1 yuan-ti abomination"),
        new Encounter(99, 99, "1d4 water elementals"),
        new Encounter(100, 100, "1 hydra"),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 1, "1 green hag"),
        new Encounter(2, 3, "2d4 giant lizards or 2d4 giant poisonous snakes"),
        new Encounter(4, 5, "2d8 winged kobolds"),
        new Encounter(6, 7, "1d10 + 1 bullywugs with 1d8 + 1 giant frogs"),
        new Encounter(8, 9, "1 druid"),
        new Encounter(10, 10, "1d8 + 1 swarms of insects"),
        new Encounter(11, 13, "1d12 ghouls"),
        new Encounter(14, 16, "2d8 scouts"),
        new Encounter(17, 19, "2d10 orcs"),
        new Encounter(20, 22, "2d4 giant spiders"),
        new Encounter(23, 24, "Tainted water that exposes creatures that move through it to sight rot (see 'Diseases' in chapter 8 of the Dungeon Master's Guide)"),
        new Encounter(25, 27, "1d6 + 2 giant toads"),
        new Encounter(28, 30, "3d6 lizardfolk"),
        new Encounter(31, 33, "1d8 + 1 yuan-ti purebloods"),
        new Encounter(34, 36, "1d4 + 1 swarms of poisonous snakes"),
        new Encounter(37, 38, "A bloated humanoid corpse floating facedown in the water"),
        new Encounter(39, 41, "1 shambling mound"),
        new Encounter(42, 44, "1d4 + 1 will-o'-wisps"),
        new Encounter(45, 47, "2d6 crocodiles"),
        new Encounter(48, 50, "1d4 + 1 giant constrictor snakes"),
        new Encounter(51, 54, "1 lizardfolk shaman with 1d3 swarms of poisonous snakes and 1d8 + 2 lizardfolk"),
        new Encounter(55, 58, "1d8 + 1 ogres"),
        new Encounter(59, 62, "2d4 ghasts"),
        new Encounter(63, 65, "An altar partially sunk into the mud, devoted to a god that is part human and part frog"),
        new Encounter(66, 69, "1 giant crocodile"),
        new Encounter(70, 73, "1 shambling mound"),
        new Encounter(74, 77, "1 orc Eye of Gruumsh with 1d3 ogres and 2d10 + 5 orcs"),
        new Encounter(78, 80, "A torrential rain that lasts 1d6 minutes and puts out all unprotected flames within 1 mile"),
        new Encounter(81, 82, "1 young black dragon"),
        new Encounter(83, 84, "1d4 green hags with 1d6 + 1 ogres"),
        new Encounter(85, 86, "1 yuan-ti abomination"),
        new Encounter(87, 88, "1d4 + 1 wights"),
        new Encounter(89, 90, "1d6 + 1 yuan-ti malisons"),
        new Encounter(91, 93, "1d4 + 1 trolls"),
        new Encounter(94, 96, "1d10 revenants"),
        new Encounter(97, 99, "1d8 + 1 water elementals"),
        new Encounter(100, 100, "1d3 hydras"),
      ]),
      new LevelRange(2, "Level 11-20", "", [
        new Encounter(1, 10, "1d4 giant crocodiles"),
        new Encounter(11, 15, "1d3 yuan-ti abominations"),
        new Encounter(16, 20, "1d6 + 1 green hags"),
        new Encounter(21, 25, "A large, spreading tree from which 2d6 armored knights hang by the neck"),
        new Encounter(26, 30, "2d4 wights"),
        new Encounter(31, 35, "1d8 + 1 yuan-ti malisons"),
        new Encounter(36, 40, "Fog that rolls across the terrain, making the area within 1d3 miles heavily obscured for 1d4 hours"),
        new Encounter(41, 45, "1d4 revenants"),
        new Encounter(46, 50, "1d6 shambling mounds"),
        new Encounter(51, 55, "1d10 water elementals"),
        new Encounter(56, 60, "1d4 young black dragons"),
        new Encounter(61, 65, "An eerie, bat-headed idol almost completely covered by vines"),
        new Encounter(66, 70, "1d8 + 2 trolls"),
        new Encounter(71, 75, "1d3 hydras"),
        new Encounter(76, 80, "The sound of drums beating several miles away"),
        new Encounter(81, 96, "1 adult black dragon"),
        new Encounter(97, 100, "1 ancient black dragon"),
      ])
    ]),
    new Biome(7, "Underdark", "", [
      new LevelRange(1, "Underdark T1 (Level 1-4)", "", [
        new Encounter(1, 1, "1 mind flayer arcanist"),
        new Encounter(2, 2, "1d3 + 1 giant poisonous snakes"),
        new Encounter(3, 3, "1d3 giant lizards"),
        new Encounter(4, 4, "2d4 giant fire beetles"),
        new Encounter(5, 5, "1d8 + 1 flumphs"),
        new Encounter(6, 6, "1 shrieker"),
        new Encounter(7, 7, "1d12 giant rats"),
        new Encounter(8, 8, "2d4 kobolds"),
        new Encounter(9, 9, "1d8 + 1 stirges"),
        new Encounter(10, 10, "2d4 humans (tribal warriors) seeking the way to the surface, fleeing their Underdark oppressors"),
        new Encounter(11, 12, "1d10 troglodytes"),
        new Encounter(13, 14, "1d2 gray oozes"),
        new Encounter(15, 16, "3d6 stirges"),
        new Encounter(17, 18, "1d3 magma mephits"),
        new Encounter(19, 20, "1d10 goblins"),
        new Encounter(21, 22, "Orc graffiti on the walls, suggesting something rude about the mother of someone named Krusk"),
        new Encounter(23, 24, "1 swarm of insects"),
        new Encounter(25, 25, "1 deep gnome"),
        new Encounter(26, 28, "1d8 + 1 drow"),
        new Encounter(29, 30, "1d4 violet fungi"),
        new Encounter(31, 32, "1d12 kuo-toa"),
        new Encounter(33, 33, "1 rust monster"),
        new Encounter(34, 35, "A rubble-strewn passage that appears to have been recently cleared after a cave-in"),
        new Encounter(36, 37, "1d8 + 1 giant bats"),
        new Encounter(38, 39, "3d6 kobolds"),
        new Encounter(40, 41, "2d4 grimlocks"),
        new Encounter(42, 43, "1d4 + 3 swarms of bats"),
        new Encounter(44, 44, "1 dwarf prospector (scout) looking for gold"),
        new Encounter(45, 45, "1 carrion crawler or 1 gelatinous cube"),
        new Encounter(46, 46, "1d8 darkmantles or 2d4 piercers"),
        new Encounter(47, 47, "1 hell hound"),
        new Encounter(48, 48, "1d3 specters"),
        new Encounter(49, 49, "1d4 bugbears"),
        new Encounter(50, 50, "1d10 + 5 winged kobolds"),
        new Encounter(51, 51, "1d4 fire snakes"),
        new Encounter(52, 52, "2d8 + 1 troglodytes"),
        new Encounter(53, 53, "1d6 giant spiders"),
        new Encounter(54, 54, "3d6 kuo-toa"),
        new Encounter(55, 55, "1 goblin boss with 2d4 goblins"),
        new Encounter(56, 56, "4d4 grimlocks"),
        new Encounter(57, 57, "1 ochre jelly"),
        new Encounter(58, 58, "2d10 giant centipedes"),
        new Encounter(59, 59, "1 nothic or 1 giant toad"),
        new Encounter(60, 60, "1d4 myconid adults with 5d4 myconid sprouts"),
        new Encounter(61, 61, "1 minotaur skeleton or 1 minotaur"),
        new Encounter(62, 62, "3d6 drow"),
        new Encounter(63, 63, "1 mimic or 1 doppelganger"),
        new Encounter(64, 64, "1d6 + 3 hobgoblins"),
        new Encounter(65, 65, "1 intellect devourer or 1 spectator"),
        new Encounter(66, 66, "1d8 + 1 orcs"),
        new Encounter(67, 68, "A faint tapping coming from inside a nearby wall"),
        new Encounter(69, 69, "1 gibbering mouther or 1 water weird"),
        new Encounter(70, 70, "1d12 gas spores"),
        new Encounter(71, 71, "1 giant constrictor snake"),
        new Encounter(72, 72, "1d10 shadows"),
        new Encounter(73, 73, "1d3 grells"),
        new Encounter(74, 74, "1d4 wights"),
        new Encounter(75, 75, "1d8 + 1 quaggoth spore servants"),
        new Encounter(76, 76, "1d2 gargoyles"),
        new Encounter(77, 77, "1d4 ogres or 1d3 ettins"),
        new Encounter(78, 78, "1d4 dwarf explorers (veterans)"),
        new Encounter(79, 80, "An abandoned miners' camp spattered with blood and littered with the contents of 1d3 dungeoneer's packs"),
        new Encounter(81, 81, "1 chuul or 1 salamander"),
        new Encounter(82, 82, "1d4 phase spiders or 1d3 hook horrors"),
        new Encounter(83, 83, "5d4 duergar"),
        new Encounter(84, 84, "1 ghost or 1 flameskull or 1 wraith"),
        new Encounter(85, 85, "1 druid with 1 polar bear (cave bear)"),
        new Encounter(86, 86, "1 hobgoblin captain with 1d4 half-ogres and 2d10 hobgoblins"),
        new Encounter(87, 87, "1 earth elemental or 1 black pudding"),
        new Encounter(88, 88, "1 kuo-toa monitor with 1d8 + 1 kuo-toa whips"),
        new Encounter(89, 89, "1 quaggoth thonot with 1d3 quaggoths"),
        new Encounter(90, 90, "1 beholder zombie or 1 bone naga"),
        new Encounter(91, 91, "1 orc Eye of Gruumsh with 1d4 orogs and 2d8 orcs"),
        new Encounter(92, 92, "1d4 ghasts with 1d10 ghouls"),
        new Encounter(93, 95, "A reeking puddle where slimy water has dripped from the ceiling"),
        new Encounter(96, 96, "1 otyugh or 1 roper"),
        new Encounter(97, 97, "1 vampire spawn"),
        new Encounter(98, 98, "1 chimera"),
        new Encounter(99, 99, "1 mind flayer"),
        new Encounter(100, 100, "1 spirit naga"),
      ]),
      new LevelRange(2, "Level 5-10", "", [
        new Encounter(1, 1, "3d6 swarms of bats"),
        new Encounter(2, 2, "1d4 giant spiders or 1d4 giant toads"),
        new Encounter(3, 3, "1 mimic"),
        new Encounter(4, 4, "2d4 gray oozes"),
        new Encounter(5, 5, "2d10 orcs or 3d6 troglodytes"),
        new Encounter(6, 6, "3d6 grimlocks"),
        new Encounter(7, 7, "1d6 + 2 magma mephits"),
        new Encounter(8, 8, "1 goblin boss with 2d4 goblins"),
        new Encounter(9, 9, "2d4 darkmantles"),
        new Encounter(10, 10, "2d8 + 1 drow"),
        new Encounter(11, 11, "2d10 piercers"),
        new Encounter(12, 12, "1d4 minotaur skeletons"),
        new Encounter(13, 14, "3d6 deep gnomes"),
        new Encounter(15, 15, "1 druid with 1 polar bear (cave bear)"),
        new Encounter(16, 17, "3d6 orcs"),
        new Encounter(18, 18, "1 bone naga"),
        new Encounter(19, 20, "2d6 bugbears"),
        new Encounter(21, 25, "Luminescent fungi growing on the walls of a moist cave, filling it with dim light"),
        new Encounter(26, 26, "2d4 specters"),
        new Encounter(27, 27, "1d12 + 4 shadows"),
        new Encounter(28, 28, "1d3 gibbering mouthers"),
        new Encounter(29, 30, "4d4 hobgoblins"),
        new Encounter(31, 32, "1d4 carrion crawlers"),
        new Encounter(33, 34, "1 black pudding"),
        new Encounter(35, 35, "1d4 ochre jellies"),
        new Encounter(36, 40, "A patch of mold that appears yellow when light is directed toward it"),
        new Encounter(41, 41, "1d4 nothics"),
        new Encounter(42, 43, "2d8 + 1 gas spores"),
        new Encounter(44, 45, "1d3 gelatinous cubes"),
        new Encounter(46, 46, "1 ghost"),
        new Encounter(47, 48, "1 flameskull"),
        new Encounter(49, 50, "2d8 duergar"),
        new Encounter(51, 51, "1 wraith"),
        new Encounter(52, 52, "1 umber hulk"),
        new Encounter(53, 53, "1 xorn"),
        new Encounter(54, 54, "1d6 + 2 dwarf hunters (veterans) searching for trolls"),
        new Encounter(55, 55, "1 hobgoblin captain with 3d10 hobgoblins"),
        new Encounter(56, 56, "1 roper"),
        new Encounter(57, 57, "1 kuo-toa monitor with 1d4 kuo-toa whips and 1d8 + 1 kuo-toa"),
        new Encounter(58, 58, "1d3 water weirds"),
        new Encounter(59, 59, "1d4 ghasts with 1d10 ghouls"),
        new Encounter(60, 60, "1 otyugh"),
        new Encounter(61, 62, "A merchant caravan consisting of 1 drow mage, 2 drow elite warriors, and 2d10 quaggoths"),
        new Encounter(63, 63, "1d4 wights"),
        new Encounter(64, 64, "1d4 doppelgangers"),
        new Encounter(65, 65, "2d8 fire snakes"),
        new Encounter(66, 66, "1d4 spectators"),
        new Encounter(67, 67, "1 orc Eye of Gruumsh with 1d4 orogs and 2d10 + 3 orcs"),
        new Encounter(68, 68, "1d3 vampire spawn"),
        new Encounter(69, 69, "1d4 hook horrors or 1d4 minotaurs"),
        new Encounter(70, 70, "3d6 quaggoth spore servants"),
        new Encounter(71, 72, "1d3 grells"),
        new Encounter(73, 73, "1d6 + 1 intellect devourers"),
        new Encounter(74, 74, "1d10 gargoyles"),
        new Encounter(75, 75, "1 beholder zombie"),
        new Encounter(76, 77, "1 quaggoth thonot with 2d4 quaggoths"),
        new Encounter(78, 78, "1d6 ettins or 1d4 trolls"),
        new Encounter(79, 79, "1d8 + 1 phase spiders"),
        new Encounter(80, 80, "1 fomorian or 1d3 cyclopes"),
        new Encounter(81, 81, "1d4 earth elementals"),
        new Encounter(82, 82, "3d6 ogres"),
        new Encounter(83, 83, "1d4 + 1 chuuls"),
        new Encounter(84, 84, "1d10 hell hounds"),
        new Encounter(85, 85, "1d3 drow elite warriors"),
        new Encounter(86, 86, "1d4 chimeras"),
        new Encounter(87, 87, "1d4 salamanders"),
        new Encounter(88, 88, "1 cloaker"),
        new Encounter(89, 89, "2d4 wights"),
        new Encounter(90, 90, "1d4 driders"),
        new Encounter(91, 91, "1 fire giant"),
        new Encounter(92, 92, "1 grick alpha with 2d4 gricks"),
        new Encounter(93, 93, "1 mind flayer arcanist"),
        new Encounter(94, 94, "1d4 drow mages"),
        new Encounter(95, 95, "1 spirit naga"),
        new Encounter(96, 96, "1d4 mind flayers"),
        new Encounter(97, 97, "1 behir"),
        new Encounter(98, 98, "1 aboleth"),
        new Encounter(99, 99, "1 dao or 1 stone giant"),
        new Encounter(100, 100, "1 beholder"),
      ]),
      new LevelRange(3, "Level 11-16", "", [
        new Encounter(1, 2, "3d6 carrion crawlers"),
        new Encounter(3, 4, "1d6 + 1 gelatinous cubes"),
        new Encounter(5, 6, "1d8 + 2 gibbering mouthers"),
        new Encounter(7, 8, "2d8 minotaur skeletons"),
        new Encounter(9, 10, "2d6 ochre jellies"),
        new Encounter(11, 12, "2d4 doppelgangers"),
        new Encounter(13, 14, "1d4 quaggoth thonots with 1d10 + 2 quaggoths"),
        new Encounter(15, 16, "1d3 ropers"),
        new Encounter(17, 18, "3d6 gargoyles"),
        new Encounter(19, 20, "1d10 mimics"),
        new Encounter(21, 25, "A 100-foot-long ravine, 4d10 feet wide and 5d20 + 200 feet deep"),
        new Encounter(26, 27, "1 hobgoblin captain with 3d10 hobgoblins"),
        new Encounter(28, 29, "2d4 spectators"),
        new Encounter(30, 31, "3d6 ghasts"),
        new Encounter(32, 33, "2d8 intellect devourers"),
        new Encounter(34, 35, "1d3 Orc Eye of Gruumsh with 2d4 orogs and 2d10 orcs"),
        new Encounter(36, 40, "A large cave containing 2d10 extraordinarily detailed statues of various creatures"),
        new Encounter(41, 42, "1d8 + 1 kuo-toa monitors"),
        new Encounter(43, 44, "2d4 water weirds"),
        new Encounter(45, 46, "2d10 gricks"),
        new Encounter(47, 48, "3d6 nothics"),
        new Encounter(49, 50, "2d8 + 1 ogres"),
        new Encounter(51, 52, "1d6 + 2 chuuls"),
        new Encounter(53, 54, "1d8 + 1 ettins"),
        new Encounter(55, 55, "3d6 grells"),
        new Encounter(56, 56, "2d4 flameskulls"),
        new Encounter(57, 57, "2d12 dwarf soldiers (veterans) on patrol"),
        new Encounter(58, 58, "2d8 hell hounds"),
        new Encounter(59, 59, "1d10 ghosts"),
        new Encounter(60, 60, "3d4 wights"),
        new Encounter(61, 61, "3d6 phase spiders"),
        new Encounter(62, 62, "1d8 + 1 bone nagas"),
        new Encounter(63, 65, "A shrill scream followed by dark laughter"),
        new Encounter(66, 66, "1d4 chimeras"),
        new Encounter(67, 67, "1d10 black puddings"),
        new Encounter(68, 68, "3d6 minotaurs"),
        new Encounter(69, 69, "2d4 otyughs"),
        new Encounter(70, 70, "1d6 + 1 beholder zombies"),
        new Encounter(71, 71, "4d4 hook horrors"),
        new Encounter(72, 72, "1d8 + 1 umber hulks"),
        new Encounter(73, 73, "2d4 salamanders"),
        new Encounter(74, 74, "1d3 grick alphas"),
        new Encounter(75, 75, "1d6 + 2 xorn"),
        new Encounter(76, 80, "A ruined village that once belonged to deep gnomes. A search has a 50% chance of uncovering 1d3 potions of healing and a 25% chance of finding a random common magic item."),
        new Encounter(81, 81, "2d4 earth elementals"),
        new Encounter(82, 82, "1d3 spirit nagas"),
        new Encounter(83, 83, "1d8 + 1 cyclopes"),
        new Encounter(84, 84, "1d6 + 2 trolls"),
        new Encounter(85, 85, "2d4 stone giants"),
        new Encounter(86, 86, "2d4 wraiths"),
        new Encounter(87, 87, "1d4 fomorians"),
        new Encounter(88, 88, "1d3 drow mages with 1d4 drow elite warriors"),
        new Encounter(89, 89, "1d10 vampire spawn"),
        new Encounter(90, 90, "1d3 cloakers"),
        new Encounter(91, 91, "1d4 fire giants"),
        new Encounter(92, 92, "1 mind flayer arcanist with 1d6 + 1 mind flayers"),
        new Encounter(93, 93, "1d4 dao"),
        new Encounter(94, 94, "1d8 + 1 driders"),
        new Encounter(95, 95, "1d3 behirs"),
        new Encounter(96, 96, "1d4 aboleths"),
        new Encounter(97, 97, "1 beholder"),
        new Encounter(98, 98, "1 young red shadow dragon"),
        new Encounter(99, 99, "1 death tyrant"),
        new Encounter(100, 100, "1 purple worm"),
      ]),
      new LevelRange(0, "Level 17-20", "", [
        new Encounter(1, 1, "1d4 grick alphas"),
        new Encounter(2, 2, "2d8 spectators"),
        new Encounter(3, 4, "3d6 minotaurs or 2d8 kuo-toa monitors"),
        new Encounter(5, 6, "2d8 grells"),
        new Encounter(7, 8, "2d10 phase spiders"),
        new Encounter(9, 10, "4d4 hell hounds"),
        new Encounter(11, 12, "1d6 + 2 ropers"),
        new Encounter(13, 14, "2d10 wights"),
        new Encounter(15, 16, "3d6 doppelgangers"),
        new Encounter(17, 18, "1d8 + 1 chimeras"),
        new Encounter(19, 20, "1d4 cloakers"),
        new Encounter(21, 21, "1d4 hobgoblin captains with 5d10 hobgoblins"),
        new Encounter(22, 23, "1d8 + 1 earth elementals"),
        new Encounter(24, 25, "2d4 vampire spawn"),
        new Encounter(26, 27, "3d6 minotaurs"),
        new Encounter(28, 30, "A 30-foot-tall inverted black pyramid floating 1 inch above the floor in a large cave"),
        new Encounter(31, 32, "1d10 beholder zombies"),
        new Encounter(33, 34, "1d4 mind flayer arcanists"),
        new Encounter(35, 36, "1d6 + 2 otyughs"),
        new Encounter(37, 38, "1d12 trolls"),
        new Encounter(39, 40, "1d10 wraiths"),
        new Encounter(41, 43, "A beautiful obsidian sculpture of a panther lying on the floor"),
        new Encounter(44, 45, "1d4 drow mages with 1d6 drow elite warriors"),
        new Encounter(46, 47, "1d4 spirit nagas"),
        new Encounter(48, 49, "1d8 + 1 salamanders"),
        new Encounter(50, 51, "2d4 umber hulks"),
        new Encounter(52, 53, "1d10 xorn"),
        new Encounter(54, 56, "1 young red shadow dragon"),
        new Encounter(57, 59, "2d4 fomorians"),
        new Encounter(60, 62, "1d8 + 1 driders"),
        new Encounter(63, 65, "1d20 + 20 spiders crawling on the walls of a web-filled cave"),
        new Encounter(66, 68, "1d4 fire giants"),
        new Encounter(69, 70, "1d10 mind flayers"),
        new Encounter(71, 73, "2d4 stone giants"),
        new Encounter(74, 76, "1d12 cyclopes"),
        new Encounter(77, 80, "A large cave in which stands a 50-foot-tall idol of Blibdoolpoolp"),
        new Encounter(81, 85, "1d3 dao"),
        new Encounter(86, 90, "1d4 beholders"),
        new Encounter(91, 93, "1d4 behirs"),
        new Encounter(94, 96, "1 death tyrant"),
        new Encounter(97, 99, "1d3 purple worms"),
        new Encounter(100, 100, "2d4 aboleths"),
      ])
    ]),
    new Biome(32, "Underwater", "", [
      new LevelRange(1, "Level 1-4", "", [
        new Encounter(1, 10, "3d6 quippers"),
        new Encounter(11, 14, "2d4 steam mephits"),
        new Encounter(15, 18, "1d4 sahuagin"),
        new Encounter(19, 22, "2d6 merfolk"),
        new Encounter(23, 25, "2d4 corpses of drowned sailors tangled in kelp"),
        new Encounter(26, 29, "2d4 constrictor snakes"),
        new Encounter(30, 33, "1d4 reef sharks"),
        new Encounter(34, 37, "1 swarm of quippers"),
        new Encounter(38, 40, "A bed of enormous clams"),
        new Encounter(41, 45, "1d10 merfolk with 1d3 giant sea horses"),
        new Encounter(46, 50, "1 giant octopus"),
        new Encounter(51, 55, "1 merrow"),
        new Encounter(56, 60, "1 plesiosaurus"),
        new Encounter(61, 65, "2d10 pieces of corroded brass dinnerware littering the bottom"),
        new Encounter(66, 70, "1 giant constrictor snake"),
        new Encounter(71, 75, "1 sea hag"),
        new Encounter(76, 80, "A school of silvery fish darting through the water"),
        new Encounter(81, 85, "1d4 hunter sharks"),
        new Encounter(86, 90, "1 sahuagin priestess with 2d4 sahuagin"),
        new Encounter(91, 96, "1d4 killer whales"),
        new Encounter(97, 98, "1 giant shark"),
        new Encounter(99, 99, "1 water elemental"),
        new Encounter(100, 100, "1 sahuagin baron"),
      ]),
      new LevelRange(2, "Level 5-10", "", [
        new Encounter(1, 2, "3d6 steam mephits"),
        new Encounter(3, 4, "1d10 sahuagin"),
        new Encounter(5, 6, "1 giant octopus"),
        new Encounter(7, 8, "3d6 constrictor snakes"),
        new Encounter(9, 10, "2d10 merfolk with 1d4 giant sea horses"),
        new Encounter(11, 15, "1d4 sea hags"),
        new Encounter(16, 20, "2d4 swarms of quippers"),
        new Encounter(21, 25, "A sunken galleon with a 50% chance of a random treasure hoard inside (roll on the Treasure Hoard: Challenge 5-10 table in chapter 7 of the Dungeon Master's Guide)"),
        new Encounter(26, 30, "1d4 plesiosauruses"),
        new Encounter(31, 35, "3d6 reef sharks"),
        new Encounter(36, 40, "An abandoned bathysphere"),
        new Encounter(41, 50, "1d4 giant constrictor snakes"),
        new Encounter(51, 55, "2d4 hunter sharks"),
        new Encounter(56, 60, "1d3 sahuagin priestesses with 2d10 sahuagin"),
        new Encounter(61, 65, "An empty castle made from coral"),
        new Encounter(66, 70, "1d4 killer whales"),
        new Encounter(71, 75, "1d10 merrow"),
        new Encounter(76, 80, "An eerie statue of a squatting humanoid, with bat wings on its back and tentacles sprouting from its face"),
        new Encounter(81, 85, "1d4 water elementals"),
        new Encounter(86, 90, "1 sahuagin baron with 2d8 sahuagin"),
        new Encounter(91, 96, "1d4 giant sharks"),
        new Encounter(97, 99, "1 marid"),
        new Encounter(100, 100, "1 storm giant"),
      ]),
      new LevelRange(3, "Level 11-20", "", [
        new Encounter(1, 10, "1 sahuagin baron with 1d4 sahuagin priestesses and 2d10 sahuagin"),
        new Encounter(11, 35, "1d10 killer whales"),
        new Encounter(36, 40, "A ghost ship passing overhead, containing 2d6 + 10 ghosts"),
        new Encounter(41, 60, "1d6 giant sharks"),
        new Encounter(61, 65, "A 1-mile-radius sphere of effervescent water that allows air-breathing creatures to breathe water while in the sphere"),
        new Encounter(66, 75, "1d10 water elementals"),
        new Encounter(76, 80, "A shimmering, blue-green portal to the Elemental Plane of Water"),
        new Encounter(81, 90, "1d4 marids"),
        new Encounter(91, 96, "1d3 storm giants"),
        new Encounter(97, 99, "1 dragon turtle"),
        new Encounter(100, 100, "1 kraken"),
      ])
    ]),
    new Biome(8, "Urban", "", [
      new LevelRange(0, "Level 1-4", "", [
        new Encounter(1, 1, "1d6 cats"),
        new Encounter(2, 3, "1 commoner with 1d6 goats"),
        new Encounter(4, 5, "2d10 rats"),
        new Encounter(6, 6, "1 raven perched on a signpost"),
        new Encounter(7, 7, "1 commoner on a draft horse"),
        new Encounter(8, 8, "2d4 mastiffs"),
        new Encounter(9, 9, "1d2 commoners leading 1d4 mules or 1d4 ponies"),
        new Encounter(10, 10, "1 pseudodragon"),
        new Encounter(11, 11, "1 spy"),
        new Encounter(12, 13, "1d8 + 1 acolytes"),
        new Encounter(14, 14, "1d6 + 6 flying snakes"),
        new Encounter(15, 15, "3d6 kobolds"),
        new Encounter(16, 16, "2d4 giant centipedes"),
        new Encounter(17, 17, "1d8 + 1 skeletons"),
        new Encounter(18, 19, "1d6 + 2 swarms of rats"),
        new Encounter(20, 20, "1d12 zombies"),
        new Encounter(21, 25, "A peddler weighed down with a load of pots, pans, and other basic supplies"),
        new Encounter(26, 26, "1 giant wasp"),
        new Encounter(27, 28, "1 warhorse"),
        new Encounter(29, 29, "2d8 cultists"),
        new Encounter(30, 31, "3d4 giant rats"),
        new Encounter(32, 32, "2d8 stirges"),
        new Encounter(33, 33, "1d3 + 2 giant poisonous snakes"),
        new Encounter(34, 34, "1d4 + 2 swarms of bats"),
        new Encounter(35, 35, "2d4 winged kobolds"),
        new Encounter(36, 40, "A wagon loaded with apples that has a broken wheel and holds up traffic"),
        new Encounter(41, 41, "1 crocodile"),
        new Encounter(42, 43, "1 swarm of insects"),
        new Encounter(44, 45, "3d6 bandits"),
        new Encounter(46, 47, "1d3 + 2 nobles on riding horses with an escort of 1d10 guards"),
        new Encounter(48, 48, "2d4 kenku"),
        new Encounter(49, 49, "1d6 + 2 smoke mephits"),
        new Encounter(50, 50, "1d8 + 1 swarms of ravens"),
        new Encounter(51, 52, "1 wererat"),
        new Encounter(53, 54, "1d3 half-ogres"),
        new Encounter(55, 56, "1 mimic"),
        new Encounter(57, 58, "1d4 ghouls"),
        new Encounter(59, 60, "1d4 specters"),
        new Encounter(61, 62, "1d10 shadows"),
        new Encounter(63, 65, "Someone empties a chamber pot onto the street from a second-floor window"),
        new Encounter(66, 67, "1 ghast"),
        new Encounter(68, 69, "1 priest"),
        new Encounter(70, 71, "1 will-o'-wisp"),
        new Encounter(72, 73, "1d3 giant spiders"),
        new Encounter(74, 75, "1d4 yuan-ti purebloods"),
        new Encounter(76, 77, "2d4 thugs"),
        new Encounter(78, 80, "A doomsayer who preaches the end of the world from a street corner"),
        new Encounter(81, 81, "1 cambion"),
        new Encounter(82, 82, "1 vampire spawn"),
        new Encounter(83, 83, "1 couatl"),
        new Encounter(84, 84, "1 ghost"),
        new Encounter(85, 85, "1 succubus or 1 incubus"),
        new Encounter(86, 86, "1 bandit captain with 3d6 bandits"),
        new Encounter(87, 87, "1d4 + 1 cult fanatics"),
        new Encounter(88, 88, "1 knight or 1 veteran"),
        new Encounter(89, 89, "1 water weird"),
        new Encounter(90, 90, "1 wight"),
        new Encounter(91, 91, "1 mage"),
        new Encounter(92, 92, "1 shield guardian"),
        new Encounter(93, 93, "1 gladiator"),
        new Encounter(94, 94, "1 revenant"),
        new Encounter(95, 95, "2d4 gargoyles"),
        new Encounter(96, 96, "1d4 doppelgangers"),
        new Encounter(97, 97, "1 oni"),
        new Encounter(98, 98, "1 invisible stalker"),
        new Encounter(99, 99, "1d8 + 1 phase spiders"),
        new Encounter(100, 100, "1 assassin"),
      ]),
      new LevelRange(1, "Level 5-10", "", [
        new Encounter(1, 2, "1d10 kenku"),
        new Encounter(3, 4, "2d6 giant centipedes"),
        new Encounter(5, 6, "2d8 skeletons"),
        new Encounter(7, 8, "1d6 swarms of bats and 1d6 swarms of rats"),
        new Encounter(9, 10, "3d6 winged kobolds"),
        new Encounter(11, 13, "2d4 specters"),
        new Encounter(14, 16, "1d4 wights"),
        new Encounter(17, 19, "4d4 acolytes on draft horses"),
        new Encounter(20, 22, "3d6 giant centipedes"),
        new Encounter(23, 25, "A talkative urchin, badgering passersby to serve as their guide through the community for a price of 1 sp"),
        new Encounter(26, 28, "1d10 spies"),
        new Encounter(29, 31, "3d6 crocodiles"),
        new Encounter(32, 34, "1d6 + 2 swarms of insects"),
        new Encounter(35, 37, "2d4 smoke mephits"),
        new Encounter(38, 40, "A noble shouts 'Stop! Thief!'' at a fleeing scoundrel (bandit)"),
        new Encounter(41, 43, "1 succubus or 1 incubus"),
        new Encounter(44, 46, "1d10 half-ogres"),
        new Encounter(47, 49, "2d10 giant wasps"),
        new Encounter(50, 51, "4d10 zombies"),
        new Encounter(52, 53, "1d4 knights on warhorses"),
        new Encounter(54, 55, "1d4 + 1 water weirds"),
        new Encounter(56, 57, "1d8 + 1 mimics"),
        new Encounter(58, 59, "2d8 giant spiders"),
        new Encounter(60, 61, "3d6 shadows"),
        new Encounter(62, 65, "An actor leans out from a second-story window to call to passersby, announcing a show"),
        new Encounter(66, 67, "1 bandit captain with 3d8 bandits"),
        new Encounter(68, 69, "1d10 will-o'-wisps"),
        new Encounter(70, 71, "2d4 priests"),
        new Encounter(72, 74, "3d6 yuan-ti purebloods"),
        new Encounter(75, 76, "2d10 thugs"),
        new Encounter(77, 80, "A fortune-teller reads cards for those who pay a price of 1 sp"),
        new Encounter(81, 81, "1d3 gladiators"),
        new Encounter(82, 82, "1d4 + 1 couatls"),
        new Encounter(83, 83, "1d8 ghosts"),
        new Encounter(84, 84, "2d4 doppelgangers"),
        new Encounter(85, 85, "1d6 +2 phase spiders"),
        new Encounter(86, 86, "2d4 veterans"),
        new Encounter(87, 87, "1d8 ghasts with 2d6 ghouls"),
        new Encounter(88, 88, "3d6 gargoyles"),
        new Encounter(89, 89, "2d10 cult fanatics"),
        new Encounter(90, 90, "3d6 wererats"),
        new Encounter(91, 91, "1 assassin"),
        new Encounter(92, 92, "1d3 invisible stalkers"),
        new Encounter(93, 93, "1 gray slaad"),
        new Encounter(94, 94, "1 young silver dragon"),
        new Encounter(95, 95, "1d4 cambions or 1d4 revenants"),
        new Encounter(96, 96, "3d6 wights"),
        new Encounter(97, 97, "1 archmage"),
        new Encounter(98, 98, "2d4 vampire spawn or 1d4 oni"),
        new Encounter(99, 99, "1 mage with 1 shield guardian"),
        new Encounter(100, 100, "1 rakshasa or 1 vampire"),
      ]),
      new LevelRange(2, "Level 11-16", "", [
        new Encounter(1, 1, "1 mimic"),
        new Encounter(2, 5, "1 bandit captain with 5d10 bandits, all on riding horses"),
        new Encounter(6, 10, "1d10 knights on warhorses (one knight is a doppelganger)"),
        new Encounter(11, 13, "1d8 succubi or 1d8 incubi"),
        new Encounter(14, 16, "3d6 cult fanatics"),
        new Encounter(17, 19, "1d10 wights"),
        new Encounter(20, 22, "3d6 wererats"),
        new Encounter(23, 25, "A distant boom followed by a plume of smoke rising from the other side of the community"),
        new Encounter(26, 28, "1d8 + 1 ghosts"),
        new Encounter(29, 31, "2d10 gargoyles"),
        new Encounter(32, 34, "1d6 + 2 water weirds"),
        new Encounter(35, 37, "1d4 + 4 will-o'-wisps"),
        new Encounter(38, 40, "Street performers putting on a puppet show, involving two puppets beating each other with sticks to the amusement of the gathered crowd"),
        new Encounter(41, 43, "2d4 couatls"),
        new Encounter(44, 46, "2d8 ghasts"),
        new Encounter(47, 51, "1d8 + 1 veterans"),
        new Encounter(52, 55, "3d4 priests"),
        new Encounter(56, 58, "2d4 cambions"),
        new Encounter(59, 61, "1d10 revenants"),
        new Encounter(62, 65, "2d4 phase spiders"),
        new Encounter(66, 69, "A scruffy commoner that ducks into an alley to make a purchase from a suspicious-looking figure"),
        new Encounter(70, 72, "1d8 invisible stalkers"),
        new Encounter(73, 75, "1d8 + 1 gladiators"),
        new Encounter(76, 80, "Two farmers trading blows over the price of potatoes (50% chance for one farmer to be a retired assassin)"),
        new Encounter(81, 82, "1d4 young silver dragons"),
        new Encounter(83, 84, "1d4 assassins"),
        new Encounter(85, 86, "1d8 oni"),
        new Encounter(87, 88, "1d4 mages with 1d4 shield guardians"),
        new Encounter(89, 90, "1d10 vampire spawn"),
        new Encounter(91, 92, "1 adult silver dragon"),
        new Encounter(93, 94, "1d4 gray slaadi"),
        new Encounter(95, 96, "1 spellcaster vampire or 1 warrior vampire"),
        new Encounter(97, 97, "1 archmage speeding down the street on a riding horse, blasting 1d4 guards with spells"),
        new Encounter(98, 98, "1 rakshasa"),
        new Encounter(99, 99, "1 vampire"),
        new Encounter(100, 100, "1 ancient silver dragon"),
      ]),
      new LevelRange(3, "Level 17-20", "", [
        new Encounter(1, 5, "1d10 invisible stalkers"),
        new Encounter(6, 10, "1d10 revenants"),
        new Encounter(11, 14, "1d6 + 2 gladiators"),
        new Encounter(15, 18, "2d4 cambions"),
        new Encounter(19, 22, "2d6 succubi or 2d6 incubi"),
        new Encounter(23, 25, "A witch (archmage) who zooms overhead on a broom of flying"),
        new Encounter(26, 30, "1d4 gray slaadi"),
        new Encounter(31, 35, "2d8 couatls"),
        new Encounter(36, 40, "A distraught parent who rushes up to people, begging for help for a child who fell into the sewer"),
        new Encounter(41, 45, "1d3 young silver dragons"),
        new Encounter(46, 50, "3d6 ghosts"),
        new Encounter(51, 55, "1 adult silver dragon"),
        new Encounter(56, 60, "1d4 mages with 1d4 shield guardians"),
        new Encounter(61, 65, "An aggressive merchant who hawks wares to passersby, claiming to be the purveyor of the finest silks in all the land"),
        new Encounter(66, 70, "1 ancient silver dragon"),
        new Encounter(71, 75, "3d6 vampire spawn"),
        new Encounter(76, 80, "A patrol of 2d10 guards marching up the street, searching for someone or something"),
        new Encounter(81, 85, "1d10 assassins"),
        new Encounter(86, 90, "1d4 + 1 gray slaadi"),
        new Encounter(91, 93, "1d10 oni"),
        new Encounter(94, 96, "1 spellcaster vampire or 1 warrior vampire"),
        new Encounter(97, 97, "1d4 archmages"),
        new Encounter(98, 98, "1d3 rakshasas"),
        new Encounter(99, 99, "1d4 vampires"),
        new Encounter(100, 100, "1 tarrasque"),
      ])
    ])
  ];

  constructor() { }
}
